-- SQL script to create the 'resident' table for Retirement Communities CRM
CREATE TABLE resident (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    community_id uuid REFERENCES community(id) NOT NULL,
    first_name text,
    last_name text,
    preferred_name text,
    prefix text,
    suffix text,
    date_of_birth date,
    gender text,
    nationality text,
    marital_status text,
    spouse_name text,
    spouse_contact_number text,
    identity_document_type text,
    identity_document_number text,
    identity_document_expiry date,
    primary_phone text,
    alternate_phone text,
    primary_email text,
    permanent_address_line1 text,
    permanent_address_line2 text,
    permanent_address_city text,
    permanent_address_country_subdivision text,
    permanent_address_postal_code text,
    blood_group text,
    primary_physician_name text,
    primary_physician_contact text,
    emergency_contact_name text,
    emergency_contact_phone text,
    emergency_contact_relationship text,
    status text CHECK (status IN ('Active', 'Inactive')) NOT NULL,
    start_date date,
    end_date date,
    notes text,
    created_datetime timestamptz DEFAULT now(),
    modified_datetime timestamptz DEFAULT now(),
    created_by uuid,
    modified_by uuid,
    photo_blob bytea
);
